"""Reading and summarising the measured ingest rates.

``data/ingest_rates.csv`` holds one row per clock hour per fleet for a single
representative day:

    hour_utc,fleet,events,payload_bytes

``events`` is the number of events observed **during that whole hour**, and
``payload_bytes`` is the total uncompressed payload of those events, also for
the whole hour. Neither column is a rate per second.

Only rows whose ``fleet`` matches ``PlannerConfig.billable_fleet`` describe real
customer traffic; the other fleets are synthetic replay traffic generated by the
load harness and must never be counted towards capacity.
"""

from __future__ import annotations

import csv
import math
from dataclasses import dataclass
from pathlib import Path

SECONDS_PER_HOUR = 3600


@dataclass(frozen=True)
class HourSample:
    hour_utc: int
    fleet: str
    events: int
    payload_bytes: int


def load_samples(path: str | Path = "data/ingest_rates.csv") -> list[HourSample]:
    rows: list[HourSample] = []
    with Path(path).open(newline="", encoding="utf-8") as fh:
        for rec in csv.DictReader(fh):
            rows.append(
                HourSample(
                    hour_utc=int(rec["hour_utc"]),
                    fleet=rec["fleet"].strip(),
                    events=int(rec["events"]),
                    payload_bytes=int(rec["payload_bytes"]),
                )
            )
    if not rows:
        raise ValueError(f"{path}: no rows")
    return rows


def billable(samples: list[HourSample], fleet: str) -> list[HourSample]:
    kept = [s for s in samples if s.fleet == fleet]
    if not kept:
        raise ValueError(f"no rows for fleet {fleet!r}")
    return kept


def peak_hour(samples: list[HourSample]) -> HourSample:
    """The busiest hour by event count."""
    return max(samples, key=lambda s: s.events)


def peak_events_per_second(samples: list[HourSample]) -> int:
    """Sustained event rate of the busiest hour, rounded up to a whole event/s."""
    return math.ceil(peak_hour(samples).events / SECONDS_PER_HOUR)


def average_payload_bytes(samples: list[HourSample]) -> int:
    """Mean uncompressed payload of one event across the whole day.

    Rounded **up** to a whole byte: a fractional byte of headroom is never
    something we are willing to give back.
    """
    events = sum(s.events for s in samples)
    payload = sum(s.payload_bytes for s in samples)
    if events <= 0:
        raise ValueError("cannot average payload over zero events")
    return math.ceil(payload / events)


def daily_events(samples: list[HourSample]) -> int:
    """Total events over the measured day."""
    return sum(s.events for s in samples)
